---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: openjdk
    tag: '8'
    username: jvalance
    password: 226137@kKk

inputs:
- name: duck-hub

run:
  path: duck-hub/detect.sh
