---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: maven
    tag: latest

inputs:
- name: duck-hub

outputs:
- name: mvn-package-output

caches:
- path: duck-hub/target

run:
  path: mvn
  args: ["-f", "duck-hub/pom.xml", "package"]

